name: rl
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - line_profiler
  - matplotlib>=3.0.0
  - notebook
  - numba
  - numpy>=1.16.0
  - pip
  - python>=3.6.0
  - pytorch>=1.4.0
  - scikit-learn>=0.21.0
  - scipy>=1.2.0
  - torchvision>=0.4.0
  - tqdm
  - pip:
    - gym[atari]>=0.17.0
    - Box2D
    - black
    - configargparse
    - tensorboard
